// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProjetoTesteDev.DataContext;

#nullable disable

namespace ProjetoTesteDev.Migrations
{
    [DbContext(typeof(SqlServerDbContext))]
    partial class SqlServerDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ProjetoTesteDev.Model.ItemConsumidoModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("MesaId")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Valor")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("MesaId");

                    b.ToTable("ItensConsumidos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            MesaId = 1,
                            Nome = "Cerveja",
                            Valor = 10.5m
                        },
                        new
                        {
                            Id = 2,
                            MesaId = 1,
                            Nome = "Petisco",
                            Valor = 25.0m
                        },
                        new
                        {
                            Id = 3,
                            MesaId = 2,
                            Nome = "Refrigerante",
                            Valor = 7.0m
                        });
                });

            modelBuilder.Entity("ProjetoTesteDev.Model.MesaModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Aberta")
                        .HasColumnType("bit");

                    b.Property<DateTime>("HorarioAbertura")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("HorarioFechamento")
                        .HasColumnType("datetime2");

                    b.Property<string>("Numero")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Mesas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Aberta = true,
                            HorarioAbertura = new DateTime(2025, 1, 1, 14, 30, 0, 0, DateTimeKind.Unspecified),
                            Numero = "M001"
                        },
                        new
                        {
                            Id = 2,
                            Aberta = false,
                            HorarioAbertura = new DateTime(2025, 1, 1, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            HorarioFechamento = new DateTime(2025, 1, 1, 13, 0, 0, 0, DateTimeKind.Unspecified),
                            Numero = "M002"
                        });
                });

            modelBuilder.Entity("ProjetoTesteDev.Model.UsuarioModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SenhaHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Usuarios");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "admin@teste.com",
                            Nome = "Admin",
                            SenhaHash = "$2b$10$9u3sj4iXBo67dnpTXrnfjess1we2nID95Ofambb9J0ZBqmAZM.3vC"
                        },
                        new
                        {
                            Id = 2,
                            Email = "tiago@teste.com",
                            Nome = "Tiago",
                            SenhaHash = "$2b$10$3RshRzxXA/M.TzXAM7UGO.sHCMCXyUIO7eeBzvogRkdmmJ.05oD.6"
                        });
                });

            modelBuilder.Entity("ProjetoTesteDev.Model.ItemConsumidoModel", b =>
                {
                    b.HasOne("ProjetoTesteDev.Model.MesaModel", "Mesa")
                        .WithMany("ItensConsumidos")
                        .HasForeignKey("MesaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Mesa");
                });

            modelBuilder.Entity("ProjetoTesteDev.Model.MesaModel", b =>
                {
                    b.Navigation("ItensConsumidos");
                });
#pragma warning restore 612, 618
        }
    }
}
